### ISSUE TITLE
Add a pre exit hook

### ISSUE THREAD

**Issue by stoffeastrom** [shellscape/mocha-chrome#14]
- [x] This is a **feature** request

### For Features; What is the motivation and/or use-case for the feature?
To be able to extract coverage I have to override `exit` like this
```javascript
async exit(code) {
    const { Runtime } = runner.client;
    const { result: { value }} = await Runtime.evaluate({ expression: 'window.__coverage__', returnByValue: true });
    this.closed = true;
    await this.client.close();
    await this.instance.kill();

    this.bus.emit('exit', 1);
  }
```
it would be nice to have some kind of pre exit hook instead

```javascript
async evaluateExit() {
  await Promise.resolve();
}
```
this way I don't have to worry about changes in the existing `MochaChrome`. Maybe even send this with `options` so I don't have to extend the class.

```javascript
const runner = new MochaChrome({
  async preExitHook() {
    const { result: { value }} = await Runtime.evaluate({ expression: 'window.__coverage__', 
  }
});
```
Let me know if you need more info.

**Comment by shellscape** [comment]
@stoffeastrom I think we can definitely add that. I'm thinking that we could extend `EventEmitter` and emit several different events. eg:

```
const runner = new MochaChrome({...});

runner.on('ended', ( ?? ) => {
...
});
```

`ended` would basically be "before exit," or "when tests have ended," and in line with how the code is structured. What parameters do you think would be useful in those events?

**Comment by stoffeastrom** [comment]
I think we need to separate `events` and `interceptors`. Emitting `events` is great for fire and forget but in this particular case it's more an `interceptor` that be `async` and thus halt the exiting until it's finished. This `interceptor` concept could be expand in different places. For example it might be possible to `intercept` the file loading and `instrument` the files for `coverage`. I will think more about the parameters for `events` .

**Comment by shellscape** [comment]
If you want to "intercept" (what we call "proxying" in JavaScript) a method then you're going about it the correct way; proxy the function and then call the original within your proxy. That's the pattern. I'm willing to add events but I'm not willing to add proxying as part of the lib, that's up to users to do.

**Comment by dietergeerts** [comment]
@shellscape , they're hooks, and can be very useful for extracting coverage. It's what you had to do in mocha-phantomjs too.
