### ISSUE TITLE
Unicode characters become garbled on Windows

### ISSUE THREAD

**Issue by jgranick** [shellscape/mocha-chrome#18]
* Operating System: Windows 10
* Node Version: v8.9.3
* NPM Version: 5.6.0
* mocha Version: 4.0.1
* mocha-chrome Version: 1.0.2

- [ ] This is a **feature** request
- [X] This is a **bug**

### Code

```js
  // code
```

### Expected Behavior

Mocha test results display in Unicode, similar to the regular `mocha` command

```
ClipboardFormats
      ✓ should compile
```

### Actual Behavior

Unicode characters are obscured in output

```
ClipboardFormats
      âœ“ should compile
```

### For Bugs; How can we reproduce the behavior?

Run `mocha-chrome` on a Windows system, I think, is all that is needed to reproduce the issue

**Comment by shellscape** [comment]
Thanks for the issue, but someone who runs Windows is going to have to step in and submit a PR to resolve this one.

**Comment by nathanboktae** [comment]
Not only that, but the terminal app you're using could affect that, as well as the current character set and font. Does it still repro using a good terminal like [cmder](http://cmder.net/) ?

**Comment by RikkiGibson** [comment]
I see the expected behavior in cmder on a pretty recent Windows 10.

**Comment by jgranick** [comment]
I believe it works on Windows without using `mocha-chrome`, perhaps because of this (or a similar) workaround:

https://github.com/mochajs/mocha/blob/d8157d0a2eca0b1c23564baca33352bf4442decb/lib/reporters/base.js#L75-L86

**Comment by jgranick** [comment]
This occurs on Ubuntu as well, when using `npm` to execute the mocha-chrome task.

This minor patch resolves it:

https://github.com/jgranick/mocha-chrome/commit/0394b2cd952fa317fe1a1360567d1abe5b2f4cfe

Perhaps there is a more elegant solution long-term, but this improves the quality of the library a lot for nearly all the systems I've tested.

**Comment by shellscape** [comment]
I've been slow to review this (baby on the way, renovating house). So, apologies this is still sitting unreviewed. I've set some time aside to run this on a VM or two, and on my Mac system as well, to verify the assertions in the PR. Due diligence calls for that as maintainer I believe, given the discrepancies in experience that you three have shared.

**Comment by jgranick** [comment]
Sorry for the apparent rush. Congratulations on the baby! 😁
