### ISSUE TITLE
test failure results in orphaned chrome.exe processes

### ISSUE THREAD

**Issue by Spongman** [shellscape/mocha-chrome#24]
> Please note that this template is not optional. If you proceed with this form,
please fill out **_all_** fields, or your issue may be closed as "invalid."
Please do not delete this template. Please do remove this header to acknowledge this message.

* Operating System: win64
* Node Version: 10.0.0
* NPM Version: 5.6.0
* mocha Version: 3.5.3
* mocha-chrome Version: 0.2.1

- [x] This is a **bug**

### Expected Behavior
chrome processes are killed after test failure

### Actual Behavior
chrome processes are left running

### For Bugs; How can we reproduce the behavior?

i'm pretty sure the issue is due to the fact that `exit()` is async.

if you add `console.log` calls and a `try`/`catch` to `exit`, like this:
```javascript
  async exit (code) {
    console.log('exit ' + code);
    this.closed = true;
    try {
      console.log('close');
      await this.client.close();
      console.log('closed');
    }
    finally {
      console.log('kill');
      await this.instance.kill();
      console.log('killed');
    }

    this.bus.emit('exit', 1);
  }
}
```

then it _only_ prints `close` - the process exits before the async `close()` call returns.

this is because `exit` isn't `await`ed:

```javascript
    bus.on('ended', stats => {
      this.ended = true;
      this.exit(stats.failures);
    });
```

however, adding an `await` here:
```javascript
    bus.on('ended', async stats => {
      this.ended = true;
      await this.exit(stats.failures);
    });
```

doesn't help because `Nanobus` doesn't support chaining async methods.

the runner looks like this:
```javascript
  grunt.registerMultiTask('mochaChrome', async function() {
    var done = this.async();

    try {
      var options = this.data.options;

      for (var testURL of options.urls) {
        var my_opts = Object.assign({}, options);
        my_opts.urls = undefined;
        my_opts.url = testURL;
        my_opts.chromeFlags = ['--no-sandbox', '--mute-audio'];
        my_opts.logLevel = 'trace';
        var runner = new MochaCrome(my_opts);
        var result = new Promise((resolve, reject) => {
          runner.on('ended', function(stats) {
            if (stats.failures) {
              reject(stats);
            } else {
              resolve(stats);
            }
          });
          runner.on('failure', reject);
        });

        (async function () {
          await runner.connect();
          await runner.run();
        })();

        await result;
      }

      done();
    }
    catch (e) {
      if (e instanceof Error) {
        done(e);
      } else {
        done(new Error(e));
      }
    }
  })
```

**Comment by shellscape** [comment]
Hm, I don't have that issue on my end. If you can create a failing test case and a fix, please submit a PR for both.

**Comment by nathanboktae** [comment]
It does account for that by emitting another event called `exit` after the process [actually exits here](https://github.com/shellscape/mocha-chrome/blob/0f596aa942babf6b95bce14707a7f4ccc6efcfb8/index.js#L161). You should wait for that event before exiting your grunt task.

**Comment by Spongman** [comment]
i just based my code off the test code here: https://github.com/shellscape/mocha-chrome/blob/master/test/api.js. is there another, more complete sample i can use that works correctly in this case?

**Comment by Spongman** [comment]
also, if the `close()` promise isn't ever getting resolved, when does the `this.instance.kill();` line run?

maybe i'm missing something, but i don't see how this can ever work in the error case.

**Comment by nathanboktae** [comment]
that should also wait for `exit`. It's just a race condition if you're listening on just `ended`. Mocha doesn't exit anymore explicity, so without `--exit` it should actually eventually wait for all the chrome processes to exit. I bet there are multiple at a time, and maybe the CI test run does have a process hanging around.

**Comment by Spongman** [comment]
> It does account for that by emitting another event called exit after the process actually exits here

i think you're missing my point: **that code never gets called.**

https://github.com/shellscape/mocha-chrome/blob/0f596aa942babf6b95bce14707a7f4ccc6efcfb8/index.js#L158-L161

the first `await` (L158) results in a `Promise` being returned from that function, but (in the test failure case) that `Promise` is promptly dropped on the floor (by Nanobus). it is _never_ resolved and neither L159 nor L161 are executed. there's no race condition. the `exit` bus event is never fired.

**Comment by shellscape** [comment]
@Spongman a better way to handle your frustration (that's what I'm sensing) would have been to create a failing test case and submit a fix for it. of course, there are always alternatives you can also use, including `mocha-headless-chrome` which works in a similar manner. this is a community-run, open-source project that people donate their time to when they can. it's free, and we're not always going to be able to predict, nor understand what someone else is reporting, so community contributions are key to improving the project. please bear that in mind in the future for any project you use.
