### ISSUE TITLE
Ability to save results to file, like mocha-phantomjs

### ISSUE THREAD

**Issue by dietergeerts** [shellscape/mocha-chrome#25]
* Operating System: Windows 10
* Node Version: v8.11.2
* NPM Version: v6.1.0
* mocha Version: v5.2.0
* mocha-chrome Version: v1.1.0

- [x] This is a **feature** request
- [ ] This is a **bug**

### Expected Behavior

Having the ability to save the test results to disk, so you can see the progress in your CI tool.

### Actual Behavior

As far as I can see, we can't do this, the reporter will always report on the console.

### For Features; What is the motivation and/or use-case for the feature?

To track test progress in our CI tool

**Comment by shellscape** [comment]
Happy to review a PR for a new reporter that does this.

**Comment by nathanboktae** [comment]
It's not a concern of a reporter (to an extent) what stream it's outputted to. Its mainly passing down a stream or writer along that is available.

That said do check to see if using your she'll to pipe is sufficient.

**Comment by dietergeerts** [comment]
Just letting know that I skip this package. It's not great to use. For example, when there is an error in one of the tests, it breaks. It should not break and run everything else, so we can collect the resuls and svae them to file. This is one of the bigger things needed in your CI chain to keep track of the status....

I was able to get to the following: (which imho should not be done through a script...)
```
const fs = require('fs');
const MochaChrome = require('mocha-chrome');

let code = 0;
let result = '';

const runner = new MochaChrome({
  chromeFlags: [],
  mocha: { useColors: true, reporter: 'xunit' },
  url: 'file://' + fs.realpathSync('dist-test/index.html'),
});

// Will be called by the reporter on each extra output.
// As mocha-chrome doesn't have the ability to save to file,
// we'll collect the content and save that to file ourselves.
runner.on('mocha', content => {
  result += content;
});

// When mocha is done, ended is called with the overall stats.
// Failures is the amount of them, and code > 0 means failed to node.
runner.on('ended', stats => {
  code = stats.failures;
});

// When there is another failure other than assertions,
// this is called, so then we'll set the code to 1.
runner.on('failure', () => {
  code = 1;
});

// All tests are done and the runner is finished.
// We need to exit the process here, but doing this too early will not let you
// get the whole result of the reporter, because mocha-chrome is event based,
// and the exit don't wait for mocha to be finished outputting the results.
// This is the really SAD part of event systems and the wrong place to use them.
runner.on('exit', () => {
  setTimeout(
    () => {
      fs.writeFileSync('test-results/junitresults.xml', result, 'utf-8');
      process.exit(code);
    },
    1000,
  );
});

(async function run() {
  await runner.connect();
  await runner.run();
})();
```

**Comment by shellscape** [comment]
@dietergeerts I'm not aware of any package or open source project that takes kindly to people posting comments along the lines of "your package is not good, I will not use it." It's not a loss to the project that you don't want to use it, and comments of those type are immensely disrespectful. That may be OK in your circles, but it is not welcome here.
