### ISSUE TITLE
With xunit reporter, output is inconsistent, and output option can't be set

### ISSUE THREAD

**Issue by acthp** [shellscape/mocha-chrome#34]
* Operating System: ubuntu 14.04
* Node Version: 8.11.3
* NPM Version: 5.6.0
* mocha Version: 6.1.2
* mocha-chrome Version: 2.0.0

- [x] This is a **feature** request
- [x] This is a **bug**

### Code

```
./node_modules/.bin/mocha-chrome --reporter xunit --reporter-options output=report.xml build/index.html
```

### Expected Behavior
xml report written to report.xml

### Actual Behavior
xml is written to stdout, and is truncated. There appears to be a race of some sort. From run to run, the output may be two lines or forty lines, but never the complete report.

The reporter works fine outside mocha-chrome, with the xml being output consistently to the console.

### For Bugs; How can we reproduce the behavior?
Use xunit reporter.

### For Features; What is the motivation and/or use-case for the feature?
The point of xunit reporter is to write results to a machine-readable file for CI. If there's no way to write to a file, it defeats the point. Redirecting stdout to a file works poorly, because other things in the framework write to stdout, corrupting the xml. E.g.
```
Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
```

**Comment by shellscape** [comment]
Happy to review a PR to resolve this.
