### ISSUE TITLE
mocha's output is always uncolorified

### ISSUE THREAD

**Issue by gamtiq** [shellscape/mocha-chrome#40]
- Operating System (or Browser): macOS Mojave, Chrome
- Node Version: 10.15.3
- mocha-chrome Version: 2.1.0

### How Do We Reproduce?
Call
```
mocha-chrome http://some-server/some-path/some-page.html
```
Then call
```
mocha-chrome http://some-server/some-path/some-page.html --no-colors
```

### Expected Behavior

mocha's output from both calls is uncolorified.

### Actual Behavior

mocha's output from the first call should be colorified.
mocha's output from the second call shouldn't be colorified.

This problem was introduced by ffe4d83.
The correct fix is in #38.

**Comment by shellscape** [comment]
Sorry, but that's not correct. Works fine on my end. Feel free to fork if it's different for you.

**Comment by gamtiq** [comment]
Do you have colorified output when calling `mocha-chrome` without `--no-colors` option?
