### ISSUE TITLE
Add support of Node 6.x

### ISSUE THREAD

**Issue by pgn-vole** [shellscape/mocha-chrome#8]
Would it be possible to add support of Node 6.x ?
It is the current LTS and people in large companies (like myself) might be stuck on it. That would be a shame to not let them use this nice libary :)

**Comment by shellscape** [comment]
Thanks for the kind words. Unfortunately I'm only interested in supporting version of Node that support async/await natively. The differences in ES6 feature support between 6 and 8 is pretty extensive.

**Comment by pgn-vole** [comment]
What about using a transpiler like babel ? The source code will be identical and the output of the build will be compatible with Node 6.x .

**Comment by shellscape** [comment]
@pgn-vole Unfortunately that's not something that's in the card for this module. I'd encourage you to take the fight to your company and get them on the latest version.

**Comment by shellscape** [comment]
82a62e2e1f5f3f8a8b8bc1d4a97a78711a2cb207

> `mocha-chrome`requires Node v8.0.0 or higher. Unfortunately the project won't be supporting a lower version number at this time. If you're in a situation where Node cannot be upgraded on a production server, not to worry! `mocha-chrome` is a dev tool, which means you can use tools like [NVM](https://github.com/creationix/nvm) and [nodenv](https://github.com/nodenv/nodenv) to manage your installed versions, and temporarily switch to v8+ to run tests on your machine. Most modern CI environments also support specifying the version of Node to run.
